jobs:
  build:
    container:
      image: snowstep/llvm@${{ needs.digest.outputs.llvm }}
    name: Build
    needs:
      - digest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - env:
          DEBIAN_FRONTEND: noninteractive
        name: Install dependent packages to build
        run: |
          apt-fast update
          apt-fast upgrade -y
          apt-fast install --no-install-recommends -y make
      - name: Build
        run: |
          make -j7
      - id: built_cache_id
        name: Cache built binary
        uses: actions/cache@v3
        with:
          key: ${{ github.sha }}
          path: |
            dumpelf
            elf.ini
  digest:
    name: Acquire digest of the latest llvm image
    outputs:
      llvm: ${{ steps.llvm.outputs.digest }}
    runs-on: ubuntu-latest
    steps:
      - id: llvm
        name: Acquire digest of the latest snowstep/llvm@jammy
        run: |
          digest=$(
            curl -s https://hub.docker.com/v2/namespaces/snowstep/repositories/llvm/tags \
              | jq -cr '[.results[]|select(.name=="jammy").images[]|select(.architecture=="amd64")]|max_by(.last_pushed).digest'
          )
          printf 'digest=%s\n' $digest | tee -a $GITHUB_OUTPUT
name: Build
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.editorconfig'
      - '.gitattributes'
      - '.gitignore'
      - 'LICENSE'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.editorconfig'
      - '.gitattributes'
      - '.gitignore'
      - 'LICENSE'
