jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          echo deb http://apt.llvm.org/focal/ llvm-toolchain-focal-snapshot main | sudo tee /etc/apt/sources.list.d/llvm.list > /dev/null
          echo deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal-snapshot main | sudo tee -a /etc/apt/sources.list.d/llvm.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y clang-16 libc++-16-dev libc++abi-16-dev libunwind-16-dev lld-16
      - name: Build
        run: env PATH=/usr/lib/llvm-16/bin:$PATH make -j7
      - id: built_cache_id
        name: Cache built binary
        uses: actions/cache@v3
        with:
          key: ${{ github.sha }}
          path: |
            dumpelf
            elf.ini
name: Build
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.editorconfig'
      - '.gitattributes'
      - '.gitignore'
      - 'LICENSE'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.editorconfig'
      - '.gitattributes'
      - '.gitignore'
      - 'LICENSE'
