jobs:
  coverage:
    container:
      image: snowstep/llvm@${{ needs.digest.outputs.llvm }}
    name: Check code coverages
    needs:
      - digest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - env:
          DEBIAN_FRONTEND: noninteractive
        name: Install dependent packages to build
        run: |
          apt-fast update
          apt-fast upgrade -y
          apt-fast install --no-install-recommends -y make
      - name: Coverage
        run: |
          make -j7 cover
      - if: ${{ always() }}
        name: Archive code coverages report
        uses: actions/upload-artifact@v3
        with:
          name: code-coverages-report
          path: |
            dumpelf.cov
            dumpelf.profdata
            dumpelf.proflog
            dumpelf.profraw
  digest:
    name: Acquire digest of the latest llvm image
    outputs:
      llvm: ${{ steps.llvm.outputs.digest }}
    runs-on: ubuntu-latest
    steps:
      - id: llvm
        name: Acquire digest of the latest snowstep/llvm@jammy
        run: |
          digest=$(
            curl -s https://hub.docker.com/v2/namespaces/snowstep/repositories/llvm/tags \
              | jq -cr '[.results[]|select(.name=="jammy").images[]|select(.architecture=="amd64")]|max_by(.last_pushed).digest'
          )
          printf 'digest=%s\n' $digest | tee -a $GITHUB_OUTPUT
name: Coverage
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.editorconfig'
      - '.gitattributes'
      - '.gitignore'
      - 'LICENSE'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.editorconfig'
      - '.gitattributes'
      - '.gitignore'
      - 'LICENSE'
